# Generated by Django 6.0.7 on 2026-08-04 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('category', models.CharField(choices=[('top', '上装'), ('bottom', '下装'), ('outer', '外套'), ('shoes', '鞋类'), ('accessory', '配饰'), ('underwear', '内衣')], max_length=20, verbose_name='类别')),
                ('color', models.CharField(help_text='如：黑色、白色、藏蓝', max_length=50, verbose_name='颜色')),
                ('brand', models.CharField(blank=True, default='', max_length=50, verbose_name='品牌')),
                ('season', models.CharField(choices=[('spring', '春季'), ('summer', '夏季'), ('autumn', '秋季'), ('winter', '冬季'), ('all', '四季')], default='all', max_length=10, verbose_name='适合季节')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='图片URL')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('wear_count', models.IntegerField(default=0, verbose_name='穿着次数')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '衣物',
                'verbose_name_plural': '衣物',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('occasion', models.CharField(blank=True, default='', help_text='如：上班、约会、运动、居家', max_length=50, verbose_name='场合')),
                ('weather', models.CharField(blank=True, default='', help_text='如：晴 25C', max_length=50, verbose_name='天气')),
                ('temperature', models.IntegerField(blank=True, null=True, verbose_name='温度')),
                ('mood', models.CharField(blank=True, default='', max_length=20, verbose_name='心情')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('photo_url', models.URLField(blank=True, default='', verbose_name='穿搭照URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clothes', models.ManyToManyField(related_name='outfit_logs', to='wardrobe.clothing', verbose_name='穿搭衣物')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '穿搭日记',
                'verbose_name_plural': '穿搭日记',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
