# Generated by Django 6.0.7 on 2026-08-04 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('mode', models.CharField(help_text='如：地铁、公交、自驾、骑行、步行、打车', max_length=20, verbose_name='出行方式')),
                ('destination', models.CharField(blank=True, default='', help_text='如：公司、学校', max_length=100, verbose_name='目的地')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='耗时(分钟)')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='距离(km)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='花费(元)')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commute_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通勤记录',
                'verbose_name_plural': '通勤记录',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='行程名称')),
                ('destination', models.CharField(max_length=200, verbose_name='目的地')),
                ('start_date', models.DateField(verbose_name='出发日期')),
                ('end_date', models.DateField(verbose_name='返回日期')),
                ('trip_type', models.CharField(default='travel', help_text='travel=旅行, business=出差', max_length=20, verbose_name='类型')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('ongoing', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='planned', max_length=20, verbose_name='状态')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际花费')),
                ('transport', models.CharField(blank=True, default='', help_text='如：飞机、高铁、自驾', max_length=50, verbose_name='交通方式')),
                ('accommodation', models.CharField(blank=True, default='', max_length=200, verbose_name='住宿')),
                ('companions', models.CharField(blank=True, default='', max_length=200, verbose_name='同行人')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名')),
                ('category', models.CharField(default='general', help_text='如：衣物、洗护、电子、证件、药品', max_length=30, verbose_name='分类')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('is_packed', models.BooleanField(default=False, verbose_name='已打包')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='travel.trip')),
            ],
            options={
                'verbose_name': '打包清单',
                'verbose_name_plural': '打包清单',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TripEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件名称')),
                ('date', models.DateField(verbose_name='日期')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='地点')),
                ('category', models.CharField(default='activity', help_text='如：交通、景点、餐饮、住宿、购物', max_length=30, verbose_name='类别')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='花费')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='travel.trip')),
            ],
            options={
                'verbose_name': '行程事件',
                'verbose_name_plural': '行程事件',
                'ordering': ['date', 'order', 'start_time'],
            },
        ),
    ]
