# Generated by Django 6.0.7 on 2026-08-04 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_color', models.CharField(default='#6C5CE7', max_length=7, verbose_name='头像颜色')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='昵称')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='所在城市')),
                ('bio', models.TextField(blank=True, default='', verbose_name='个人简介')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身高(cm)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='体重(kg)')),
                ('diet_preference', models.CharField(blank=True, default='', help_text='如：素食、低碳水、高蛋白、无限制', max_length=20, verbose_name='饮食偏好')),
                ('allergy', models.TextField(blank=True, default='', verbose_name='过敏食物')),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='月度预算')),
                ('commute_mode', models.CharField(blank=True, default='', help_text='如：地铁、公交、自驾、骑行、步行', max_length=20, verbose_name='通勤方式')),
                ('commute_minutes', models.IntegerField(blank=True, null=True, verbose_name='通勤时长(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
