# Generated by Django 6.0.7 on 2026-08-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_api_key',
            field=models.CharField(blank=True, default='', help_text='用于 AI 推荐（仅保存在本服务器）', max_length=200, verbose_name='AI API Key'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_api_url',
            field=models.CharField(blank=True, default='', help_text='OpenAI 兼容接口，如 https://api.deepseek.com/v1', max_length=300, verbose_name='AI API 地址'),
        ),
    ]
