# Generated by Django 6.0.7 on 2026-08-04 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('category', models.CharField(choices=[('food', '餐饮'), ('rent', '房租/房贷'), ('utility', '水电煤网'), ('transport', '交通'), ('shopping', '购物'), ('entertainment', '娱乐'), ('medical', '医疗'), ('education', '教育'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('title', models.CharField(max_length=200, verbose_name='名称')),
                ('date', models.DateField(verbose_name='日期')),
                ('payment_method', models.CharField(blank=True, default='', help_text='如：微信、支付宝、银行卡、现金', max_length=20, verbose_name='支付方式')),
                ('store', models.CharField(blank=True, default='', max_length=100, verbose_name='商家')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '支出记录',
                'verbose_name_plural': '支出记录',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名')),
                ('category', models.CharField(help_text='如：纸巾、洗护、清洁、厨房', max_length=30, verbose_name='分类')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='最低库存')),
                ('location', models.CharField(blank=True, default='', help_text='如：厨房柜、卫生间、阳台', max_length=50, verbose_name='存放位置')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='价格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '家居库存',
                'verbose_name_plural': '家居库存',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HouseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='家务名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='周期性')),
                ('frequency', models.CharField(blank=True, default='', help_text='如：每天、每周一、每月1号', max_length=20, verbose_name='频率')),
                ('interval_days', models.IntegerField(blank=True, help_text='每隔几天执行一次', null=True, verbose_name='间隔天数')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='下次到期日')),
                ('last_done_date', models.DateField(blank=True, null=True, verbose_name='上次完成日')),
                ('is_done', models.BooleanField(default=False, verbose_name='本次已完成')),
                ('priority', models.IntegerField(default=2, verbose_name='优先级(1-3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '家务待办',
                'verbose_name_plural': '家务待办',
                'ordering': ['priority', 'next_due_date'],
            },
        ),
    ]
