# Generated by Django 6.0.7 on 2026-08-04 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='菜名')),
                ('category', models.CharField(help_text='如：家常菜、汤品、主食、凉菜、甜品', max_length=30, verbose_name='分类')),
                ('cuisine', models.CharField(blank=True, default='', help_text='如：川菜、粤菜、西餐', max_length=20, verbose_name='菜系')),
                ('difficulty', models.IntegerField(default=2, verbose_name='难度(1-5)')),
                ('cook_time', models.IntegerField(default=30, verbose_name='烹饪时间(分钟)')),
                ('servings', models.IntegerField(default=2, verbose_name='份数')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='热量(大卡)')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='预算(元)')),
                ('ingredients', models.TextField(help_text='每行一个：食材名 用量', verbose_name='食材')),
                ('steps', models.TextField(help_text='每行一个步骤', verbose_name='步骤')),
                ('tags', models.CharField(blank=True, default='', help_text='逗号分隔', max_length=200, verbose_name='标签')),
                ('is_public', models.BooleanField(default=False, verbose_name='公开菜谱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '菜谱',
                'verbose_name_plural': '菜谱',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '加餐')], max_length=20, verbose_name='餐次')),
                ('custom_food', models.CharField(blank=True, default='', help_text='非菜谱时的食物名', max_length=200, verbose_name='自定义食物')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='摄入热量(大卡)')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='花费(元)')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='评分(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.recipe')),
            ],
            options={
                'verbose_name': '餐食记录',
                'verbose_name_plural': '餐食记录',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物品名')),
                ('quantity', models.CharField(default='1', max_length=50, verbose_name='数量')),
                ('category', models.CharField(blank=True, default='', help_text='如：蔬菜、肉类、调味品、日用品', max_length=30, verbose_name='分类')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='已购买')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='预估价格')),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='实际价格')),
                ('store', models.CharField(blank=True, default='', max_length=100, verbose_name='购买店铺')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='购买时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物清单',
                'verbose_name_plural': '购物清单',
                'ordering': ['is_purchased', '-created_at'],
            },
        ),
    ]
